"""
Rule-based drug knowledge base for the Prescription Agent.

Deterministic, transparent, mocked drug data used by the rule-based
strategies. NOT a source of pharmacological truth — a decision-support
heuristic that must always be reviewed by a physician before use. Designed
so a future `PharmacyDatabaseProvider` (e.g. First Databank, Lexicomp, RxNorm)
can be swapped in without changing pipeline or route code.
"""

from __future__ import annotations

from typing import Dict, FrozenSet, List, NamedTuple, Optional, Tuple


class DrugProfile(NamedTuple):
    name: str
    drug_class: str
    conditions: List[str]
    purpose: str
    evidence_source: str
    clinical_guideline: str
    alternative_drugs: List[str]
    expected_outcome: str
    confidence: float
    contraindicated_conditions: List[str]
    allergy_classes: List[str]
    cross_reactive_allergy_classes: List[str]
    inactive_ingredients: List[str]
    starting_dose: str
    maintenance_dose: str
    maximum_dose: str
    renal_adjustment: str
    hepatic_adjustment: str
    monitoring: List[str]


DRUG_PROFILES: List[DrugProfile] = [
    DrugProfile(
        name="Metformin",
        drug_class="Biguanide",
        conditions=["Type 2 Diabetes Mellitus"],
        purpose="First-line glycemic control for Type 2 Diabetes Mellitus.",
        evidence_source="ADA Standards of Medical Care in Diabetes",
        clinical_guideline="American Diabetes Association (ADA) Guidelines",
        alternative_drugs=["SGLT2 inhibitors (e.g. Empagliflozin)", "DPP-4 inhibitors (e.g. Sitagliptin)"],
        expected_outcome="Improved fasting/postprandial glucose control and reduced HbA1c over 8-12 weeks.",
        confidence=0.88,
        contraindicated_conditions=["Chronic Kidney Disease (severe, eGFR < 30)"],
        allergy_classes=["metformin"],
        cross_reactive_allergy_classes=[],
        inactive_ingredients=["povidone", "magnesium stearate"],
        starting_dose="500 mg once daily with food",
        maintenance_dose="500-1000 mg twice daily",
        maximum_dose="2000-2550 mg/day (divided doses)",
        renal_adjustment="Avoid if eGFR < 30 mL/min/1.73m^2; reduce dose if eGFR 30-45.",
        hepatic_adjustment="Use with caution in significant hepatic impairment (lactic acidosis risk).",
        monitoring=["Renal function (eGFR)", "HbA1c", "Vitamin B12 (long-term use)"],
    ),
    DrugProfile(
        name="Insulin Glargine",
        drug_class="Long-Acting Insulin",
        conditions=["Type 2 Diabetes Mellitus"],
        purpose="Basal glycemic control when oral agents are insufficient.",
        evidence_source="ADA Standards of Medical Care in Diabetes",
        clinical_guideline="American Diabetes Association (ADA) Guidelines",
        alternative_drugs=["Insulin Detemir", "Insulin Degludec"],
        expected_outcome="Stable basal glucose control with reduced fasting hyperglycemia.",
        confidence=0.8,
        contraindicated_conditions=[],
        allergy_classes=["insulin", "insulin glargine"],
        cross_reactive_allergy_classes=[],
        inactive_ingredients=["zinc", "metacresol"],
        starting_dose="0.1-0.2 units/kg once daily",
        maintenance_dose="Titrate by 1-2 units every 3 days to fasting glucose target",
        maximum_dose="Individualized — no fixed ceiling; titrate to glycemic target",
        renal_adjustment="Reduce dose in renal impairment — increased hypoglycemia risk.",
        hepatic_adjustment="Reduce dose in hepatic impairment — increased hypoglycemia risk.",
        monitoring=["Fasting glucose", "HbA1c", "Hypoglycemia symptoms"],
    ),
    DrugProfile(
        name="Lisinopril",
        drug_class="ACE Inhibitor",
        conditions=["Hypertension", "Chronic Kidney Disease", "Coronary Artery Disease"],
        purpose="Blood pressure control and renal/cardiac protection.",
        evidence_source="ACC/AHA Hypertension Guideline",
        clinical_guideline="ACC/AHA Guideline for the Management of High Blood Pressure",
        alternative_drugs=["Losartan (ARB)", "Amlodipine (CCB)"],
        expected_outcome="Reduced systolic/diastolic blood pressure and slowed renal disease progression.",
        confidence=0.85,
        contraindicated_conditions=["Pregnancy", "Bilateral renal artery stenosis"],
        allergy_classes=["lisinopril", "ace inhibitor", "ace inhibitors"],
        cross_reactive_allergy_classes=[],
        inactive_ingredients=["mannitol", "calcium phosphate"],
        starting_dose="10 mg once daily",
        maintenance_dose="20-40 mg once daily",
        maximum_dose="80 mg/day",
        renal_adjustment="Start at lower dose (2.5-5 mg) if eGFR < 30; monitor potassium and creatinine closely.",
        hepatic_adjustment="No specific adjustment; monitor as with any hepatic impairment.",
        monitoring=["Serum potassium", "Serum creatinine", "Blood pressure"],
    ),
    DrugProfile(
        name="Amlodipine",
        drug_class="Calcium Channel Blocker",
        conditions=["Hypertension", "Coronary Artery Disease"],
        purpose="Blood pressure control and anti-anginal effect.",
        evidence_source="ACC/AHA Hypertension Guideline",
        clinical_guideline="ACC/AHA Guideline for the Management of High Blood Pressure",
        alternative_drugs=["Lisinopril (ACEi)", "Hydrochlorothiazide (Thiazide)"],
        expected_outcome="Reduced blood pressure and reduced anginal symptom frequency.",
        confidence=0.83,
        contraindicated_conditions=["Cardiogenic shock", "Severe aortic stenosis"],
        allergy_classes=["amlodipine", "dihydropyridine"],
        cross_reactive_allergy_classes=[],
        inactive_ingredients=["microcrystalline cellulose"],
        starting_dose="5 mg once daily",
        maintenance_dose="5-10 mg once daily",
        maximum_dose="10 mg/day",
        renal_adjustment="No dose adjustment typically required.",
        hepatic_adjustment="Start at 2.5 mg in significant hepatic impairment.",
        monitoring=["Blood pressure", "Peripheral edema"],
    ),
    DrugProfile(
        name="Atorvastatin",
        drug_class="Statin (HMG-CoA Reductase Inhibitor)",
        conditions=["Coronary Artery Disease", "Hypertension"],
        purpose="LDL cholesterol reduction and cardiovascular risk reduction.",
        evidence_source="ACC/AHA Cholesterol Management Guideline",
        clinical_guideline="ACC/AHA Blood Cholesterol Guideline",
        alternative_drugs=["Rosuvastatin", "Ezetimibe"],
        expected_outcome="30-50% reduction in LDL cholesterol and reduced cardiovascular event risk.",
        confidence=0.87,
        contraindicated_conditions=["Active liver disease", "Pregnancy"],
        allergy_classes=["atorvastatin", "statin", "statins"],
        cross_reactive_allergy_classes=[],
        inactive_ingredients=["lactose monohydrate"],
        starting_dose="20 mg once daily",
        maintenance_dose="20-40 mg once daily",
        maximum_dose="80 mg/day",
        renal_adjustment="No dose adjustment typically required.",
        hepatic_adjustment="Contraindicated in active liver disease; monitor liver enzymes.",
        monitoring=["Liver function tests (ALT/AST)", "Lipid panel", "Muscle pain (myopathy)"],
    ),
    DrugProfile(
        name="Aspirin",
        drug_class="Antiplatelet / NSAID",
        conditions=["Coronary Artery Disease"],
        purpose="Secondary prevention of cardiovascular events via platelet inhibition.",
        evidence_source="ACC/AHA Secondary Prevention Guideline",
        clinical_guideline="ACC/AHA Guideline on Secondary Prevention",
        alternative_drugs=["Clopidogrel"],
        expected_outcome="Reduced risk of myocardial infarction and stroke recurrence.",
        confidence=0.82,
        contraindicated_conditions=["Active peptic ulcer bleeding", "Bleeding disorder"],
        allergy_classes=["aspirin", "nsaid", "nsaids", "salicylate"],
        cross_reactive_allergy_classes=["nsaid"],
        inactive_ingredients=["cellulose"],
        starting_dose="75-81 mg once daily",
        maintenance_dose="75-81 mg once daily",
        maximum_dose="325 mg/day (higher doses rarely indicated long-term)",
        renal_adjustment="Use with caution in severe renal impairment.",
        hepatic_adjustment="Use with caution in hepatic impairment (bleeding risk).",
        monitoring=["Signs of GI bleeding", "Platelet function (if indicated)"],
    ),
    DrugProfile(
        name="Atenolol",
        drug_class="Beta Blocker",
        conditions=["Hypertension", "Coronary Artery Disease"],
        purpose="Heart rate/blood pressure control and anti-anginal effect.",
        evidence_source="ACC/AHA Hypertension Guideline",
        clinical_guideline="ACC/AHA Guideline for the Management of High Blood Pressure",
        alternative_drugs=["Metoprolol", "Carvedilol"],
        expected_outcome="Reduced heart rate, blood pressure, and anginal episodes.",
        confidence=0.78,
        contraindicated_conditions=["Severe bradycardia", "Decompensated heart failure", "Severe asthma"],
        allergy_classes=["atenolol", "beta blocker", "beta blockers"],
        cross_reactive_allergy_classes=["beta blocker"],
        inactive_ingredients=["magnesium stearate"],
        starting_dose="25 mg once daily",
        maintenance_dose="50-100 mg once daily",
        maximum_dose="100 mg/day",
        renal_adjustment="Reduce dose if eGFR < 35 (renally cleared).",
        hepatic_adjustment="No specific adjustment typically required.",
        monitoring=["Heart rate", "Blood pressure", "Signs of bronchospasm"],
    ),
    DrugProfile(
        name="Salbutamol",
        drug_class="Short-Acting Beta Agonist (SABA)",
        conditions=["Asthma / Reactive Airway Disease"],
        purpose="Rapid relief of bronchospasm and wheezing.",
        evidence_source="GINA Global Strategy for Asthma Management",
        clinical_guideline="Global Initiative for Asthma (GINA) Guidelines",
        alternative_drugs=["Levalbuterol"],
        expected_outcome="Rapid symptomatic relief of wheeze/dyspnea within 5-15 minutes.",
        confidence=0.84,
        contraindicated_conditions=[],
        allergy_classes=["salbutamol", "albuterol"],
        cross_reactive_allergy_classes=[],
        inactive_ingredients=["propellant (HFA)"],
        starting_dose="2 puffs (100-200 mcg) as needed",
        maintenance_dose="2 puffs every 4-6 hours as needed",
        maximum_dose="8 puffs (800 mcg)/day for as-needed use",
        renal_adjustment="No adjustment typically required.",
        hepatic_adjustment="No adjustment typically required.",
        monitoring=["Frequency of use (overuse indicates poor control)", "Heart rate"],
    ),
    DrugProfile(
        name="Budesonide",
        drug_class="Inhaled Corticosteroid (ICS)",
        conditions=["Asthma / Reactive Airway Disease"],
        purpose="Maintenance anti-inflammatory control to reduce exacerbation frequency.",
        evidence_source="GINA Global Strategy for Asthma Management",
        clinical_guideline="Global Initiative for Asthma (GINA) Guidelines",
        alternative_drugs=["Fluticasone", "Beclomethasone"],
        expected_outcome="Reduced airway inflammation and exacerbation frequency over weeks.",
        confidence=0.8,
        contraindicated_conditions=["Untreated systemic fungal infection"],
        allergy_classes=["budesonide", "corticosteroid"],
        cross_reactive_allergy_classes=["corticosteroid"],
        inactive_ingredients=["lactose"],
        starting_dose="200-400 mcg twice daily",
        maintenance_dose="200-400 mcg twice daily",
        maximum_dose="800 mcg twice daily (high-dose regimens)",
        renal_adjustment="No adjustment typically required.",
        hepatic_adjustment="Use with caution in severe hepatic impairment.",
        monitoring=["Growth (in children)", "Oral candidiasis", "Symptom control frequency"],
    ),
    DrugProfile(
        name="Amoxicillin",
        drug_class="Beta-Lactam Antibiotic (Penicillin)",
        conditions=["Pneumonia / Respiratory Infection", "Urinary Tract Infection"],
        purpose="Empiric treatment of susceptible bacterial infection.",
        evidence_source="IDSA/ATS Community-Acquired Pneumonia Guideline",
        clinical_guideline="IDSA/ATS Guideline for Community-Acquired Pneumonia",
        alternative_drugs=["Azithromycin", "Cephalexin"],
        expected_outcome="Clinical improvement in fever/symptoms within 48-72 hours.",
        confidence=0.79,
        contraindicated_conditions=["Mononucleosis (risk of rash)"],
        allergy_classes=["amoxicillin", "penicillin", "penicillins"],
        cross_reactive_allergy_classes=["cephalosporin"],
        inactive_ingredients=["magnesium stearate"],
        starting_dose="500 mg three times daily",
        maintenance_dose="500-875 mg twice or three times daily",
        maximum_dose="3000 mg/day",
        renal_adjustment="Extend dosing interval if eGFR < 30.",
        hepatic_adjustment="No specific adjustment typically required.",
        monitoring=["Symptom resolution", "Signs of allergic reaction", "Full course completion"],
    ),
    DrugProfile(
        name="Azithromycin",
        drug_class="Macrolide Antibiotic",
        conditions=["Pneumonia / Respiratory Infection"],
        purpose="Empiric/atypical coverage for community-acquired respiratory infection.",
        evidence_source="IDSA/ATS Community-Acquired Pneumonia Guideline",
        clinical_guideline="IDSA/ATS Guideline for Community-Acquired Pneumonia",
        alternative_drugs=["Doxycycline", "Amoxicillin"],
        expected_outcome="Clinical improvement in fever/symptoms within 48-72 hours.",
        confidence=0.76,
        contraindicated_conditions=["Known QT prolongation", "Severe hepatic impairment"],
        allergy_classes=["azithromycin", "macrolide", "macrolides"],
        cross_reactive_allergy_classes=["macrolide"],
        inactive_ingredients=["magnesium stearate"],
        starting_dose="500 mg once on day 1",
        maintenance_dose="250 mg once daily on days 2-5",
        maximum_dose="500 mg/day",
        renal_adjustment="No adjustment typically required.",
        hepatic_adjustment="Avoid in severe hepatic impairment.",
        monitoring=["QT interval (if cardiac risk factors)", "Liver function", "Symptom resolution"],
    ),
    DrugProfile(
        name="Ciprofloxacin",
        drug_class="Fluoroquinolone Antibiotic",
        conditions=["Urinary Tract Infection"],
        purpose="Treatment of complicated or resistant urinary tract infection.",
        evidence_source="IDSA Guideline for Uncomplicated UTI",
        clinical_guideline="IDSA/ESCMID Guideline for Uncomplicated Cystitis and Pyelonephritis",
        alternative_drugs=["Nitrofurantoin", "Trimethoprim-sulfamethoxazole"],
        expected_outcome="Resolution of urinary symptoms within 3-5 days.",
        confidence=0.72,
        contraindicated_conditions=["Tendon disorder history", "Myasthenia gravis"],
        allergy_classes=["ciprofloxacin", "fluoroquinolone", "fluoroquinolones"],
        cross_reactive_allergy_classes=["fluoroquinolone"],
        inactive_ingredients=["magnesium stearate"],
        starting_dose="250-500 mg twice daily",
        maintenance_dose="250-500 mg twice daily for 3-7 days",
        maximum_dose="1500 mg/day",
        renal_adjustment="Reduce dose/frequency if eGFR < 30.",
        hepatic_adjustment="No specific adjustment typically required.",
        monitoring=["Renal function", "Tendon pain", "Symptom resolution"],
    ),
    DrugProfile(
        name="Nitrofurantoin",
        drug_class="Urinary Antiseptic",
        conditions=["Urinary Tract Infection"],
        purpose="First-line treatment of uncomplicated lower urinary tract infection.",
        evidence_source="IDSA Guideline for Uncomplicated UTI",
        clinical_guideline="IDSA/ESCMID Guideline for Uncomplicated Cystitis",
        alternative_drugs=["Ciprofloxacin", "Trimethoprim-sulfamethoxazole"],
        expected_outcome="Resolution of urinary symptoms within 3-5 days.",
        confidence=0.75,
        contraindicated_conditions=["eGFR < 30 (reduced efficacy/toxicity risk)"],
        allergy_classes=["nitrofurantoin"],
        cross_reactive_allergy_classes=[],
        inactive_ingredients=["lactose"],
        starting_dose="100 mg twice daily",
        maintenance_dose="100 mg twice daily for 5 days",
        maximum_dose="400 mg/day",
        renal_adjustment="Avoid if eGFR < 30 — reduced efficacy and toxicity risk.",
        hepatic_adjustment="Use with caution; rare hepatotoxicity.",
        monitoring=["Renal function", "Pulmonary symptoms (rare toxicity)"],
    ),
    DrugProfile(
        name="Ferrous Sulfate",
        drug_class="Iron Supplement",
        conditions=["Anemia"],
        purpose="Replenish iron stores in iron-deficiency anemia.",
        evidence_source="WHO Guideline on Iron Supplementation",
        clinical_guideline="WHO Guideline: Iron Supplementation in Anaemia",
        alternative_drugs=["Ferrous Gluconate", "IV Iron (if oral intolerant)"],
        expected_outcome="Rise in hemoglobin of ~1 g/dL every 2-3 weeks with adherence.",
        confidence=0.74,
        contraindicated_conditions=["Hemochromatosis", "Active GI bleeding (relative)"],
        allergy_classes=["ferrous sulfate", "iron"],
        cross_reactive_allergy_classes=[],
        inactive_ingredients=["sucrose"],
        starting_dose="325 mg (65 mg elemental iron) once daily",
        maintenance_dose="325 mg once or twice daily",
        maximum_dose="325 mg three times daily",
        renal_adjustment="No adjustment typically required.",
        hepatic_adjustment="No adjustment typically required.",
        monitoring=["Hemoglobin", "Ferritin", "GI tolerance (constipation)"],
    ),
    DrugProfile(
        name="Levothyroxine",
        drug_class="Thyroid Hormone Replacement",
        conditions=["Thyroid Disorder"],
        purpose="Hormone replacement in hypothyroidism.",
        evidence_source="American Thyroid Association Guideline",
        clinical_guideline="American Thyroid Association (ATA) Guidelines",
        alternative_drugs=["Liothyronine (adjunct, rarely first-line)"],
        expected_outcome="Normalized TSH and resolution of hypothyroid symptoms over 6-8 weeks.",
        confidence=0.85,
        contraindicated_conditions=["Untreated adrenal insufficiency", "Acute myocardial infarction"],
        allergy_classes=["levothyroxine"],
        cross_reactive_allergy_classes=[],
        inactive_ingredients=["lactose"],
        starting_dose="25-50 mcg once daily (lower in elderly/cardiac disease)",
        maintenance_dose="1.6 mcg/kg/day (titrated to TSH)",
        maximum_dose="Individualized — titrate to normal TSH (no fixed ceiling)",
        renal_adjustment="No adjustment typically required.",
        hepatic_adjustment="No adjustment typically required.",
        monitoring=["TSH (every 6-8 weeks until stable)", "Heart rate", "Symptom review"],
    ),
    DrugProfile(
        name="Omeprazole",
        drug_class="Proton Pump Inhibitor (PPI)",
        conditions=["Gastritis / Peptic Ulcer Disease"],
        purpose="Acid suppression for mucosal healing.",
        evidence_source="ACG Guideline for Peptic Ulcer Disease",
        clinical_guideline="American College of Gastroenterology (ACG) Guideline",
        alternative_drugs=["Pantoprazole", "Famotidine (H2 blocker)"],
        expected_outcome="Symptom relief within days; mucosal healing over 4-8 weeks.",
        confidence=0.83,
        contraindicated_conditions=[],
        allergy_classes=["omeprazole", "proton pump inhibitor"],
        cross_reactive_allergy_classes=["proton pump inhibitor"],
        inactive_ingredients=["sucrose"],
        starting_dose="20 mg once daily before breakfast",
        maintenance_dose="20-40 mg once daily",
        maximum_dose="40 mg twice daily (severe cases)",
        renal_adjustment="No adjustment typically required.",
        hepatic_adjustment="Consider dose reduction in severe hepatic impairment.",
        monitoring=["Symptom resolution", "Magnesium (long-term use)"],
    ),
    DrugProfile(
        name="Sumatriptan",
        drug_class="Triptan (5-HT1 Agonist)",
        conditions=["Migraine / Neurological Headache Disorder"],
        purpose="Acute abortive treatment of migraine attacks.",
        evidence_source="American Headache Society Guideline",
        clinical_guideline="American Headache Society (AHS) Guideline",
        alternative_drugs=["Rizatriptan", "NSAIDs (e.g. Ibuprofen)"],
        expected_outcome="Headache relief within 2 hours in most responders.",
        confidence=0.7,
        contraindicated_conditions=["Coronary Artery Disease", "Uncontrolled Hypertension", "Stroke history"],
        allergy_classes=["sumatriptan", "triptan"],
        cross_reactive_allergy_classes=["triptan"],
        inactive_ingredients=["lactose"],
        starting_dose="50 mg at onset of headache",
        maintenance_dose="May repeat once after 2 hours if needed",
        maximum_dose="200 mg/day",
        renal_adjustment="No adjustment typically required.",
        hepatic_adjustment="Use with caution in hepatic impairment.",
        monitoring=["Cardiovascular symptoms", "Headache frequency (medication-overuse risk)"],
    ),
    DrugProfile(
        name="Ibuprofen",
        drug_class="NSAID",
        conditions=["Migraine / Neurological Headache Disorder"],
        purpose="Acute pain relief for mild-to-moderate migraine or headache.",
        evidence_source="American Headache Society Guideline",
        clinical_guideline="American Headache Society (AHS) Guideline",
        alternative_drugs=["Naproxen", "Acetaminophen"],
        expected_outcome="Pain relief within 30-60 minutes.",
        confidence=0.68,
        contraindicated_conditions=["Active peptic ulcer disease", "Chronic Kidney Disease (severe)"],
        allergy_classes=["ibuprofen", "nsaid", "nsaids"],
        cross_reactive_allergy_classes=["nsaid"],
        inactive_ingredients=["croscarmellose sodium"],
        starting_dose="400 mg every 6-8 hours as needed",
        maintenance_dose="400-600 mg every 6-8 hours as needed",
        maximum_dose="3200 mg/day (short-term use)",
        renal_adjustment="Avoid in severe renal impairment; use lowest effective dose.",
        hepatic_adjustment="Use with caution in hepatic impairment.",
        monitoring=["Renal function (chronic use)", "GI symptoms", "Blood pressure"],
    ),
    DrugProfile(
        name="Ceftriaxone",
        drug_class="Third-Generation Cephalosporin",
        conditions=["Sepsis / Systemic Infection"],
        purpose="Empiric broad-spectrum coverage for suspected sepsis pending cultures.",
        evidence_source="Surviving Sepsis Campaign Guideline",
        clinical_guideline="Surviving Sepsis Campaign International Guidelines",
        alternative_drugs=["Piperacillin-Tazobactam", "Meropenem (if resistant organisms suspected)"],
        expected_outcome="Clinical stabilization and downtrending inflammatory markers within 48-72 hours.",
        confidence=0.7,
        contraindicated_conditions=["Hyperbilirubinemic neonates"],
        allergy_classes=["ceftriaxone", "cephalosporin", "cephalosporins"],
        cross_reactive_allergy_classes=["penicillin"],
        inactive_ingredients=["arginine"],
        starting_dose="1-2 g once daily (IV)",
        maintenance_dose="2 g once daily (IV)",
        maximum_dose="4 g/day",
        renal_adjustment="No adjustment typically required (primarily biliary excretion).",
        hepatic_adjustment="Reduce dose if both hepatic and renal impairment present.",
        monitoring=["Inflammatory markers (CRP, WBC)", "Blood cultures", "Renal function"],
    ),
]


DRUG_INTERACTIONS: Dict[FrozenSet[str], Tuple[str, str, str]] = {
    frozenset({"lisinopril", "amlodipine"}): (
        "Minor",
        "Both are antihypertensives; combined use is common but may cause additive hypotension.",
        "Monitor blood pressure after initiating combination therapy.",
    ),
    frozenset({"aspirin", "ibuprofen"}): (
        "Moderate",
        "NSAIDs may reduce the cardioprotective antiplatelet effect of aspirin and increase GI bleeding risk.",
        "Avoid regular concurrent use; if needed, take aspirin at least 30-60 minutes before ibuprofen.",
    ),
    frozenset({"lisinopril", "ibuprofen"}): (
        "Moderate",
        "NSAIDs can reduce the antihypertensive effect of ACE inhibitors and increase renal impairment risk.",
        "Monitor blood pressure and renal function; use lowest effective NSAID dose for shortest duration.",
    ),
    frozenset({"metformin", "ciprofloxacin"}): (
        "Minor",
        "Fluoroquinolones may occasionally alter blood glucose control in diabetic patients.",
        "Monitor blood glucose more closely during and after antibiotic course.",
    ),
    frozenset({"levothyroxine", "ferrous sulfate"}): (
        "Moderate",
        "Iron salts bind levothyroxine in the gut and reduce its absorption.",
        "Separate administration by at least 4 hours.",
    ),
    frozenset({"levothyroxine", "omeprazole"}): (
        "Minor",
        "Reduced gastric acidity from PPIs may modestly reduce levothyroxine absorption.",
        "Take levothyroxine on an empty stomach; monitor TSH if both are long-term.",
    ),
    frozenset({"azithromycin", "atorvastatin"}): (
        "Moderate",
        "Macrolide antibiotics can increase statin plasma levels, raising myopathy/rhabdomyolysis risk.",
        "Consider temporarily withholding statin during short antibiotic course, or monitor for muscle pain.",
    ),
    frozenset({"atenolol", "salbutamol"}): (
        "Moderate",
        "Beta blockers can blunt the bronchodilator effect of beta-agonists and worsen bronchospasm risk.",
        "Prefer a cardioselective beta blocker or alternative antihypertensive in patients with reactive airway disease.",
    ),
    frozenset({"aspirin", "amoxicillin"}): (
        "Minor",
        "No clinically significant interaction expected; monitor for GI upset with concurrent use.",
        "No specific action typically required.",
    ),
    frozenset({"ciprofloxacin", "sumatriptan"}): (
        "Minor",
        "No major pharmacokinetic interaction expected; monitor for additive CNS effects.",
        "No specific action typically required.",
    ),
}


def get_drug_profile(name: str) -> Optional[DrugProfile]:
    key = (name or "").strip().lower()
    for profile in DRUG_PROFILES:
        if profile.name.lower() == key:
            return profile
    return None


class DrugKnowledgeBase:
    """Read-only accessor over the static drug profile table."""

    def all_profiles(self) -> List[DrugProfile]:
        return list(DRUG_PROFILES)

    def get(self, name: str) -> Optional[DrugProfile]:
        return get_drug_profile(name)

    def drugs_for_condition(self, condition: str) -> List[DrugProfile]:
        c = (condition or "").strip().lower()
        return [p for p in DRUG_PROFILES if any(c == cond.lower() for cond in p.conditions)]

    def interaction_between(self, drug_a: str, drug_b: str) -> Optional[Tuple[str, str, str]]:
        key = frozenset({(drug_a or "").strip().lower(), (drug_b or "").strip().lower()})
        return DRUG_INTERACTIONS.get(key)

    def all_interaction_pairs(self) -> Dict[FrozenSet[str], Tuple[str, str, str]]:
        return dict(DRUG_INTERACTIONS)
